<a href="https://colab.research.google.com/github/gauravjha201/Machine-learning-basics/blob/main/Naive_bayes_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
x,y=load_iris(return_X_y=True)
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [ ]:
x_train

array([[5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 2.2, 5. , 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2.9, 3.6, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [6.1, 3. , 4.6, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [5.3, 3.7, 1.5, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [6.4, 2.7, 5.3, 1.9],
       [5.7, 3. , 4.2, 1.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.9, 3.1, 4.9, 1.5],
       [4.6, 3.1, 1.5, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5.1, 2.5, 3. , 1.1],
       [4.6, 3.4, 1.4, 0.3],
       [6.2, 2.2, 4.5, 1.5],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 2.9, 4.2, 1.3],
       [4.8, 3. , 1.4, 0.1],
       [7.1, 3. , 5.9, 2.1],
       [6.9, 3.2, 5.7, 2.3],
       [6.5, 3. , 5.8, 2.2],
       [6.4, 2.8, 5.6, 2.1],
       [5.1, 3.8, 1.6, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [6.5, 3.2, 5.1, 2. ],
       [6.7, 3.3, 5.7, 2.1],
       [4.5, 2.3, 1.3, 0.3],
       [6.2, 3.4, 5.4, 2.3],
       [4.9, 3. , 1.4, 0.2],
       [5.7, 2.5, 5. , 2. ],
       [6.9, 3.1, 5.4, 2.1],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [7.2, 3. , 5.8, 1.6],
       [5.1, 3.5, 1.4, 0.3],
       [4.4, 3. , 1.3, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5.5, 2.3, 4. , 1.3],
       [6.8, 3.2, 5.9, 2.3],
       [7.6, 3. , 6.6, 2.1],
       [5.1, 3.5, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [5.7, 2.8, 4.5, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [5. , 3.2, 1.2, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [6.4, 2.9, 4.3, 1.3],
       [5.4, 3.4, 1.5, 0.4],
       [7.7, 2.6, 6.9, 2.3],
       [4.9, 2.4, 3.3, 1. ],
       [7.9, 3.8, 6.4, 2. ],
       [6.7, 3.1, 4.4, 1.4],
       [5.2, 4.1, 1.5, 0.1],
       [6. , 3. , 4.8, 1.8],
       [5.8, 4. , 1.2, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.1, 3.8, 1.5, 0.3],
       [4.7, 3.2, 1.6, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [5. , 3.3, 1.4, 0.2],
       [6.3, 3.4, 5.6, 2.4],
       [5.7, 2.8, 4.1, 1.3],
       [5.8, 2.7, 3.9, 1.2],
       [5.7, 2.6, 3.5, 1. ],
       [6.4, 3.2, 5.3, 2.3],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.7, 3. , 5. , 1.7],
       [5. , 3. , 1.6, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [6.7, 3.1, 5.6, 2.4],
       [5.8, 2.7, 5.1, 1.9],
       [5.1, 3.4, 1.5, 0.2],
       [6.6, 2.9, 4.6, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.9, 3.2, 4.8, 1.8],
       [6.3, 2.3, 4.4, 1.3],
       [5.5, 3.5, 1.3, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.9, 3.1, 1.5, 0.1],
       [6.3, 2.9, 5.6, 1.8],
       [5.8, 2.7, 4.1, 1. ],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2]])

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred=gnb.predict(x_test)
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]

In [ ]:
import seaborn as sns
df=sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [ ]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [ ]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [ ]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
x=df[['total_bill','tip','sex','day','time','size']]
y=df['smoker']
x,y

(     total_bill   tip     sex   day    time  size
 0         16.99  1.01  Female   Sun  Dinner     2
 1         10.34  1.66    Male   Sun  Dinner     3
 2         21.01  3.50    Male   Sun  Dinner     3
 3         23.68  3.31    Male   Sun  Dinner     2
 4         24.59  3.61  Female   Sun  Dinner     4
 ..          ...   ...     ...   ...     ...   ...
 239       29.03  5.92    Male   Sat  Dinner     3
 240       27.18  2.00  Female   Sat  Dinner     2
 241       22.67  2.00    Male   Sat  Dinner     2
 242       17.82  1.75    Male   Sat  Dinner     2
 243       18.78  3.00  Female  Thur  Dinner     2

 [244 rows x 6 columns],
 0       No
 1       No
 2       No
 3       No
 4       No
       ...
 239     No
 240    Yes
 241    Yes
 242     No
 243     No
 Name: smoker, Length: 244, dtype: category
 Categories (2, object): ['Yes', 'No'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Re-initialize train/test splits to ensure x_train, x_test, y_train, y_test are fresh categorical strings
x_train,x_test,y_train,y_test=train_test_split(x.copy(),y.copy(),test_size=0.3,random_state=10)

# LabelEncoder for the target variable 'smoker' (y)
lb3=LabelEncoder()
lb3.fit(y.astype(str))

y_train=lb3.transform(y_train.astype(str))

In [ ]:
# Only transform y_test here, as x_test feature encoding will be handled by ColumnTransformer
y_test=lb3.transform(y_test.astype(str))

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Define the ColumnTransformer to OneHotEncode 'sex', 'day', 'time' and passthrough the rest.
# Column indices: 'total_bill'(0), 'tip'(1), 'sex'(2), 'day'(3), 'time'(4), 'size'(5)
ct=ColumnTransformer(
    transformers=[('onehot', OneHotEncoder(drop='first'), [2, 3, 4])],
    remainder='passthrough'
)

import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

x_train=ct.fit_transform(x_train)

In [ ]:
x_test=ct.transform(x_test)

In [ ]:
x_test

array([[ 0.  ,  0.  ,  1.  ,  0.  ,  0.  , 16.21,  2.  ,  3.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 20.29,  3.21,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 13.81,  2.  ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 18.29,  3.76,  4.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 15.01,  2.09,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  1.  , 32.68,  5.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 19.49,  3.51,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 25.89,  5.16,  4.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 22.23,  5.  ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 24.06,  3.6 ,  3.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 23.33,  5.65,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  , 44.3 ,  2.5 ,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  1.  ,  7.56,  1.44,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  , 30.14,  3.09,  4.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 16.49,  2.  ,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  1.  , 18.64,  1.36,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  1.  , 14.52,  2.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  1.  , 13.42,  1.68,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  , 20.9 ,  3.5 ,  3.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 15.81,  3.16,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 10.27,  1.71,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  , 13.27,  2.5 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 13.37,  2.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  1.  , 11.87,  1.63,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 20.69,  5.  ,  5.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  1.  , 10.33,  2.  ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 17.92,  3.08,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  1.  , 24.08,  2.92,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  1.  , 11.69,  2.31,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 48.27,  6.73,  4.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 29.93,  5.07,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  , 28.17,  6.5 ,  3.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  8.77,  2.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 12.66,  2.5 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 19.82,  3.18,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  , 12.9 ,  1.1 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 20.65,  3.35,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  , 12.16,  2.2 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 20.49,  4.06,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 38.01,  3.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  1.  , 19.44,  3.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 45.35,  3.5 ,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  1.  , 11.17,  1.5 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 28.15,  3.  ,  5.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  1.  , 13.  ,  2.  ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 12.02,  1.97,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  0.  , 22.49,  3.5 ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 13.81,  2.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  1.  ,  9.78,  1.73,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  , 22.42,  3.48,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 17.92,  4.08,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 32.4 ,  6.  ,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  1.  , 16.47,  3.23,  3.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 25.29,  4.71,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  7.25,  1.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  0.  , 21.01,  3.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  1.  , 12.74,  2.01,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  1.  ,  7.51,  2.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 32.9 ,  3.11,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  , 10.09,  2.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 18.04,  3.  ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 11.24,  1.76,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 10.34,  1.66,  3.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 21.01,  3.5 ,  3.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 20.23,  2.01,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 40.55,  3.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  9.6 ,  4.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  , 34.81,  5.2 ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  1.  , 20.53,  4.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  1.  , 41.19,  5.  ,  5.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  , 15.06,  3.  ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  , 17.82,  1.75,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  , 26.88,  3.12,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  , 18.78,  3.  ,  2.  ]])

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred=gnb.predict(x_test)
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.6081081081081081
              precision    recall  f1-score   support

           0       0.64      0.71      0.67        42
           1       0.56      0.47      0.51        32

    accuracy                           0.61        74
   macro avg       0.60      0.59      0.59        74
weighted avg       0.60      0.61      0.60        74